introduce tftp driver
jumpstarter-dev/jumpstarter pull request #196
Opened 2024-12-15 19:19 UTC by bennyz

Simple TFTP driver to upload/download files to/from a TFTP serve.

Sample config:
```yaml
  tftp:
    type: jumpstarter_driver_tftp.driver.TftpServer
    config:
      root_dir: "/var/lib/tftpboot/"
```

2024-12-15 19:20 UTC, bennyz commented on jumpstarter/common/serde.py
> +    if isinstance(v, Generator):
Not sure about this

2024-12-15 21:22 UTC, mangelajo reviewed
Some comments, very cool to see implementation working so quickly.

Thank you benny!

2024-12-15 21:22 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +    host: str = "0.0.0.0"
Some suggestions:

I'd try to reduce configuration surface, (probably setting up a exporter is a cumbersome task, and we can try to make it work with as little tweaks as possible, while allowing for configuration), i.e.:

Make root_dir optional, if not provided, we just pick a TempDir of some sort (or a default /var/lib/jumpstarter/tftp location ? , may be tmp is problematic with ram)

Same for host. We could auto detect the default route IP (which may work on most situations), and optionally accept a specific IP (useful if the DUT is connected over a specific interface which is not the default route interface).

2024-12-15 21:22 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +        with tqdm(total=len(data), unit='B', unit_scale=True, desc=f"Uploading {filename}") as pbar:
Nice, progress bars always make waiting nicer :)

2024-12-15 21:22 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +                await self.call_async(
hehe I was meaning something different for the async here, although it's a starting point, I think we should merge it as it is and we can improve it later.

Where I think async would help in general is the driver side more than the client side

Also using the opendal adapter, I believe (if I am not wrong) it creates a stream (another connection through the router) just for pumping bytes through without waiting (like TCP windows), the advantage of this is that... if even the connection is behind some serious latency the bandwidth will be maximized,

Although, the code is a little bit complex to follow, I think we need to document and clean it up.

 in the current implementation, every chunk needs to receive the exporter side ack before the client can send the new chunk I think.

**But** we can improve that later honestly, it's an optimization.

2024-12-15 21:22 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +                await self.call_async(
This is a client example:

https://github.com/jumpstarter-dev/jumpstarter/blob/main/jumpstarter/drivers/storage/client.py#L26

And this is a driver example:

https://github.com/jumpstarter-dev/jumpstarter/blob/main/contrib/drivers/dutlink/jumpstarter_driver_dutlink/driver.py#L131

You'd also avoid the b64 enc/dec of parameters

2024-12-15 21:22 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +                await self.call_async(
Link to the resource call on the driver: 
https://github.com/jumpstarter-dev/jumpstarter/blob/main/jumpstarter/driver/base.py#L183

This is what connects it back to the client side stream

2024-12-16 12:24 UTC, bennyz commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +        with tqdm(total=len(data), unit='B', unit_scale=True, desc=f"Uploading {filename}") as pbar:
now that I use the opendal adapter it doens't look as good[1] (does not consider total size), but I'll look into that separately 

[1] read: 30.9MB [00:06, 4.96MB/s]

2024-12-16 12:26 UTC, bennyz commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +                await self.call_async(
done :)

perhaps it should be made clearer somehow, that the upload/download isn't done with tftp

2024-12-16 13:31 UTC, mangelajo requested changes
It looks great, just a couple of comments, this already doesn't feel like draft ;)

2024-12-16 13:31 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +    async def finalize_file(self, filename: str):
I think this one isn't used anymore.

2024-12-16 13:31 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +        return self.host
I'd also add a get_port, so if the exporter configuration is using a different port to 69 it can still be discovered by the test.

I believe that uboot can be tuned to a different destination port with the tftpdstp env var.

2024-12-16 13:31 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +    pass
nice exception structuring, which I think we have been lacking in some areas

I would remove this one, we don't use it, and two calls to start may be idempotent. (i.e. one test starts, the next just finds it started but could potentially call to start again, nothing should fail)

2024-12-16 13:31 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +        with tqdm(total=len(data), unit='B', unit_scale=True, desc=f"Uploading {filename}") as pbar:
Ah, yes, that may need improvement, the progress bar is a bit meeh

2024-12-16 13:31 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/client.py
> +                await self.call_async(
right, it may look like we are using put via tftp.

I'd start documenting with docstrings , then it's very easy to expose it in docs.jumpstarter.dev

i.e. https://docs.jumpstarter.dev/api-reference/contrib/ustreamer.html

(From https://github.com/jumpstarter-dev/jumpstarter/tree/main/docs/source/api-reference and https://raw.githubusercontent.com/jumpstarter-dev/jumpstarter/refs/heads/main/docs/source/api-reference/contrib/ustreamer.md )

2024-12-16 13:35 UTC, bennyz commented on contrib/drivers/tftp/Dockerfile
> +  VIRTUAL_ENV=/jumpstarter uv pip install /dist/*.whl
yeah, I took everything from the template, I'll remove the stuff that isn't in other drivers in `contrib`

2024-12-17 18:45 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +        return self.host
you forgot about get_port

Everything else looks great.

2024-12-17 18:45 UTC, mangelajo requested changes
one tiny nit, everything else looks great, I guess from our chat still we need to figure out the timeouts.

2024-12-17 19:58 UTC, bennyz commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +        return self.host
it's on L#119, or did you mean something else?

2024-12-18 10:29 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/driver.py
> +        return self.host
The one on L174 actually :) I must have been running the last time.

2024-12-18 10:33 UTC, mangelajo commented on contrib/drivers/tftp/src/jumpstarter_driver_tftp/server_test.py
> +            b'../../../etc/passwd\x00' +
👍

2024-12-18 12:02 UTC, mangelajo approved these changes

2024-12-18 12:03 UTC, mangelajo commented
@bennyz there is one ruff error, and if possible squash the commits, as the current merge queue doesn't seem to accept squash merging.

2024-12-18 12:47 UTC, mangelajo approved these changes

2024-12-18 12:51 UTC, merged